import test from "node:test";
import assert from "node:assert/strict";
import { buildRivhitImport, validateRivhitImport } from "../rivhit-export.js";

const template = Array(186).fill("x").join("\t"), mapping = { "811": "הוצאות משרדיות" }, row = { active: true, highlights: [{ field: "total_amount" }], rawNet: "100", rawVat: "18", values: ["2026-09-12", "811", "ציוד", "ספק", "123", "INV-9912", "77", "118", "100", "18", "100", "100"] };
test("создаёт CP1255 Rivhit TXT с 186 колонками", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [row], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns.length, 186); assert.equal(columns[3], "811"); assert.equal(columns[134], "811"); assert.equal(columns[6], "118.00"); assert.equal(columns[135], "הוצאות משרדיות"); });
test("нормализует дату DD/MM/YYYY для Rivhit", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, values: ["28/08/2026", ...row.values.slice(1)] }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[7], "28/08/26"); assert.equal(columns[0], "2026"); assert.equal(columns[1], "8"); });
test("принимает дату DD/MM/YY и относит её к 2000-м годам", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, values: ["19/08/26", ...row.values.slice(1)] }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[7], "19/08/26"); assert.equal(columns[0], "2026"); });
test("экспортирует строку без маркеров документа", () => { const result = buildRivhitImport({ templateText: template, rows: [{ ...row, highlights: [] }], mapping }); assert.ok(result.length > 0); });
test("экспорт берёт пересчитанные признанные суммы, а не исходные", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, rawNet: "610.17", rawVat: "109.83", values: [...row.values.slice(0, 7), "180.00", "152.54", "27.46", "25", "25"] }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[6], "180.00"); assert.equal(columns[154], "152.54"); assert.equal(columns[155], "27.46"); });
test("не наследует ни одного старого значения из заполненной строки шаблона", () => { const dirty = Array(186).fill("старое значение"); dirty[52] = "4514254.21"; dirty[63] = "-1382439.42"; dirty[30] = "31/05/98"; dirty[120] = "OLD-ID-7788"; const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: dirty.join("\t"), rows: [row], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[52], "0"); assert.equal(columns[63], "0"); assert.equal(columns[30], "0"); assert.equal(columns[120], "0"); assert.equal(columns[140], "0"); assert.equal(columns.some((value) => value.includes("старое") || value.startsWith("-")), false); });
test("не создаёт TXT с отрицательным числом", () => { const negative = { ...row, values: [...row.values.slice(0, 7), "-118", "-100", "-18", "100", "100"] }; assert.throws(() => buildRivhitImport({ templateText: template, rows: [negative], mapping }), /מספר שלילי/); });
test("предварительная проверка возвращает все ошибки активных строк", () => { const invalid = [{ ...row, tableRow: 4, values: ["", ...row.values.slice(1)] }, { ...row, tableRow: 9, values: [...row.values.slice(0, 7), "-118", "-100", "-18", "100", "100"] }]; const issues = validateRivhitImport({ templateText: template, rows: invalid, mapping }); assert.equal(issues.length, 2); assert.match(issues[0].message, /בשורה 4/); assert.match(issues[1].message, /בשורה 9/); });
