import test from "node:test";
import assert from "node:assert/strict";
import { buildRivhitImport, validateRivhitImport } from "../rivhit-export.js";

const template = Array(186).fill("x").join("\t"), mapping = { "811": "הוצאות משרדיות" }, row = { active: true, highlights: [{ field: "total_amount" }], rawNet: "100", rawVat: "18", values: ["2026-09-12", "811", "ציוד", "ספק", "123", "INV-9912", "77", "118", "100", "18", "100", "100"] };
test("создаёт CP1255 Rivhit TXT с 186 колонками", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [row], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns.length, 186); assert.equal(columns[3], "811"); assert.equal(columns[134], "811"); assert.equal(columns[6], "118.00"); assert.equal(columns[135], "הוצאות משרדיות"); });
test("нормализует дату DD/MM/YYYY для Rivhit", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, values: ["28/08/2026", ...row.values.slice(1)] }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[7], "28/08/26"); assert.equal(columns[0], "2026"); assert.equal(columns[1], "8"); });
test("ставит месяц декларации во все поля месяца, независимо от даты документа", () => { const rows = [{ ...row, values: ["28/08/2026", ...row.values.slice(1)] }, { ...row, values: ["03/05/2026", ...row.values.slice(1)] }], text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows, mapping, declarationMonth: "2026-04" })), records = text.trimEnd().split("\r\n").map((record) => record.split("\t")); assert.deepEqual(records.map((columns) => [columns[1], columns[185]]), [["4", "4"], ["4", "4"]]); assert.deepEqual(records.map((columns) => columns[7]), ["28/08/26", "03/05/26"]); });
test("принимает дату DD/MM/YY и относит её к 2000-м годам", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, values: ["19/08/26", ...row.values.slice(1)] }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[7], "19/08/26"); assert.equal(columns[0], "2026"); });
test("экспортирует строку без маркеров документа", () => { const result = buildRivhitImport({ templateText: template, rows: [{ ...row, highlights: [] }], mapping }); assert.ok(result.length > 0); });
test("заменяет типографские символы, недоступные в Windows-1255", () => { const values = [...row.values]; values[2] = "ספק ״מבחן״ — ☺"; const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, values }], mapping })); assert.match(text, /ספק "מבחן" - \?/); });
test("экспорт берёт пересчитанные признанные суммы, а не исходные", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, rawNet: "610.17", rawVat: "109.83", values: [...row.values.slice(0, 7), "180.00", "152.54", "27.46", "25", "25"] }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[6], "180.00"); assert.equal(columns[154], "152.54"); assert.equal(columns[155], "27.46"); });
test("записывает в колонку 158 эффективную ставку НДС", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, vatPercent: "18", values: [...row.values.slice(0, 7), "118.00", "106.00", "12.00", "66.67", "100"] }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[157], "12.00"); });
test("оставляет нулевую ставку только для строки без НДС", () => { const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: template, rows: [{ ...row, rawNet: "100", rawVat: "0", vatPercent: "0", values: [...row.values.slice(0, 7), "100.00", "100.00", "0.00", "0", "100"] }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[157], "0.00"); });
test("сохраняет из шаблона обязательные короткие флаги, но не старые данные", () => { const source = Array(186).fill("0"); source[20] = source[36] = source[49] = source[92] = source[96] = source[109] = "1"; source[136] = source[138] = source[156] = "4"; source[151] = "2"; source[52] = "4514254.21"; source[30] = "31/05/98"; source[135] = "שם ישן"; const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: source.join("\t"), rows: [{ ...row, vatPercent: "18" }], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[20], "1"); assert.equal(columns[136], "4"); assert.equal(columns[151], "2"); assert.equal(columns[179], "1"); assert.equal(columns[180], "1.00"); assert.equal(columns[52], ""); assert.equal(columns[30], ""); assert.equal(columns[135], "הוצאות משרדיות"); });
test("не наследует ни одного старого значения из заполненной строки шаблона", () => { const dirty = Array(186).fill("старое значение"); dirty[52] = "4514254.21"; dirty[63] = "-1382439.42"; dirty[30] = "31/05/98"; dirty[120] = "OLD-ID-7788"; const text = new TextDecoder("windows-1255").decode(buildRivhitImport({ templateText: dirty.join("\t"), rows: [row], mapping })), columns = text.trimEnd().split("\t"); assert.equal(columns[52], ""); assert.equal(columns[63], ""); assert.equal(columns[30], ""); assert.equal(columns[120], ""); assert.equal(columns[140], ""); assert.equal(columns.some((value) => value.includes("старое") || value.startsWith("-")), false); });
test("не создаёт TXT с отрицательным числом", () => { const negative = { ...row, values: [...row.values.slice(0, 7), "-118", "-100", "-18", "100", "100"] }; assert.throws(() => buildRivhitImport({ templateText: template, rows: [negative], mapping }), /מספר שלילי/); });
test("предварительная проверка возвращает все ошибки активных строк", () => { const invalid = [{ ...row, tableRow: 4, values: ["", ...row.values.slice(1)] }, { ...row, tableRow: 9, values: [...row.values.slice(0, 7), "-118", "-100", "-18", "100", "100"] }]; const issues = validateRivhitImport({ templateText: template, rows: invalid, mapping }); assert.equal(issues.length, 2); assert.match(issues[0].message, /בשורה 4/); assert.match(issues[1].message, /בשורה 9/); });
