import { normalizeWorkspaceConfig, validateRivhitTemplateText } from "./workspace-core.js";

const configName = "workspace.json", databaseName = "rivhit-local-workspaces-v1", decoder = new TextDecoder("windows-1255");
function openDatabase() { return new Promise((resolve, reject) => { const request = indexedDB.open(databaseName, 1); request.onupgradeneeded = () => request.result.createObjectStore("settings"); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function setting(key, value) { const database = await openDatabase(); return new Promise((resolve, reject) => { const transaction = database.transaction("settings", value === undefined ? "readonly" : "readwrite"), request = value === undefined ? transaction.objectStore("settings").get(key) : transaction.objectStore("settings").put(value, key); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }).finally(() => database.close()); }
async function validateTemplateFile(file) { const result = validateRivhitTemplateText(decoder.decode(await file.arrayBuffer())); if (!result.valid) throw new Error(result.error); }
async function readConfig(directory) { const handle = await directory.getFileHandle(configName), result = normalizeWorkspaceConfig(JSON.parse(await (await handle.getFile()).text())); if (!result.valid) throw new Error(result.error); return result.config; }
async function writeConfig(directory, config) { const handle = await directory.getFileHandle(configName, { create: true }), writable = await handle.createWritable(); try { await writable.write(JSON.stringify(config, null, 2)); } finally { await writable.close(); } }
async function ensureAccess(directory) { let permission = await directory.queryPermission({ mode: "readwrite" }); if (permission !== "granted") permission = await directory.requestPermission({ mode: "readwrite" }); if (permission !== "granted") throw new Error("לא ניתנה הרשאה לתיקיית הלקוח."); }
function option(value, text) { return new Option(text, value); }

export function setupWorkspaceControls({ select, templateButton, creationPanel, createButton, deleteButton, grantDeleteAccessButton, clientNameInput, clientActivityInput, summary, templateSummary, onWorkspace, onTemplate, onDeleted, onError }) {
  if (!("showDirectoryPicker" in window) || !("showOpenFilePicker" in window) || !("indexedDB" in window)) { select.disabled = true; templateButton.disabled = true; summary.textContent = "נדרש Edge או Chrome עם גישה לתיקיות מקומיות."; return; }
  let clients = [];
  const renderClients = (selectedId = "") => { select.replaceChildren(option("", "בחר לקוח…")); clients.forEach((client) => select.add(option(client.id, client.clientName))); select.add(option("__open__", "פתיחת תיקיית לקוח קיימת…")); select.add(option("__create__", "יצירת לקוח חדש…")); select.value = selectedId; };
  // The selector must be useful even while IndexedDB restores saved handles.
  // A fresh localhost origin has no stored handles, and a blocked database must
  // not prevent the user from opening or creating a client in this session.
  renderClients();
  const persistClient = async (directory, config, parent = null) => { const previous = clients.find((client) => client.id === config.clientId), record = { id: config.clientId || crypto.randomUUID(), clientName: config.clientName, directory, parent: parent || previous?.parent || null, entryName: directory.name }; clients = [...clients.filter((client) => client.id !== record.id), record]; await setting("clients", clients); renderClients(record.id); return record; };
  const useWorkspace = async (directory, config, parent = null) => { await ensureAccess(directory); const record = await persistClient(directory, config, parent); grantDeleteAccessButton.hidden = Boolean(record.parent); const workspace = { directory, config, saveSettings: async ({ businessActivity, businessKind }) => { const result = normalizeWorkspaceConfig({ ...config, businessActivity, businessKind }); if (!result.valid) throw new Error(result.error); Object.assign(config, result.config); await writeConfig(directory, config); } }; summary.textContent = `נבחר לקוח: «${config.clientName}».`; summary.classList.add("workspace-ready"); onWorkspace(workspace); };
  const openExisting = async () => { const directory = await window.showDirectoryPicker({ mode: "readwrite", startIn: "documents" }); await useWorkspace(directory, await readConfig(directory)); };
  const createNew = async () => { const clientName = clientNameInput.value.trim(), businessActivity = clientActivityInput.value.trim(); if (!clientName || !businessActivity) throw new Error("יש למלא שם לקוח וסוג פעילות."); const parent = await window.showDirectoryPicker({ mode: "readwrite", startIn: "documents" }), directory = await parent.getDirectoryHandle(clientName, { create: true }), config = { schemaVersion: 1, clientId: crypto.randomUUID(), clientName, businessActivity, businessKind: "home" }; try { await readConfig(directory); throw new Error("בתיקייה זו כבר קיים לקוח. יש לפתוח אותו במקום ליצור מחדש."); } catch (error) { if (error.message.includes("כבר קיים")) throw error; if (error.name !== "NotFoundError") throw error; } await writeConfig(directory, config); await directory.getDirectoryHandle("batches", { create: true }); await useWorkspace(directory, config, parent); creationPanel.hidden = true; clientNameInput.value = ""; clientActivityInput.value = ""; };
  select.addEventListener("change", async () => { try { creationPanel.hidden = select.value !== "__create__"; if (select.value === "__open__") await openExisting(); else if (select.value && select.value !== "__create__") { const client = clients.find((item) => item.id === select.value); if (client) await useWorkspace(client.directory, await readConfig(client.directory), client.parent); } } catch (error) { if (error.name !== "AbortError") onError(`לא ניתן לבחור לקוח: ${error.message}`); renderClients(); } });
  createButton.addEventListener("click", async () => { try { await createNew(); } catch (error) { if (error.name !== "AbortError") onError(`לא ניתן ליצור לקוח: ${error.message}`); } });
  grantDeleteAccessButton.addEventListener("click", async () => { try { const client = clients.find((item) => item.id === select.value); if (!client) throw new Error("יש לבחור לקוח."); summary.textContent = `בחר תיקיית אב שמכילה את התיקייה «${client.clientName}», ולא את תיקיית הלקוח עצמה.`; const parent = await window.showDirectoryPicker({ mode: "readwrite", startIn: "documents" }), target = await parent.getDirectoryHandle(client.entryName || client.directory.name); if (!await target.isSameEntry(client.directory)) throw new Error("התיקייה שנבחרה אינה תיקיית האב של הלקוח."); client.parent = parent; await setting("clients", clients); grantDeleteAccessButton.hidden = true; summary.textContent = "הרשאה למחיקת לקוח נשמרה."; summary.classList.add("workspace-ready"); } catch (error) { if (error.name !== "AbortError") { const message = `לא ניתן לחבר הרשאה למחיקה: ${error.message}`; summary.textContent = message; summary.classList.remove("workspace-ready"); onError(message); } } });
  deleteButton.addEventListener("click", async () => { try { const client = clients.find((item) => item.id === select.value); if (!client) throw new Error("יש לבחור לקוח למחיקה."); if (!client.parent) throw new Error("ללקוח ותיק זה חסרה הרשאה למחיקת תיקיית האב. יש ללחוץ תחילה על «חיבור הרשאה למחיקה» פעם אחת."); const parent = client.parent; await ensureAccess(parent); const entryName = client.entryName || client.directory.name, target = await parent.getDirectoryHandle(entryName); if (!await target.isSameEntry(client.directory)) throw new Error("התיקייה שנבחרה אינה תיקיית הלקוח. המחיקה בוטלה."); if (!window.confirm(`למחוק לצמיתות את «${client.clientName}» ואת כל ההיסטוריה והחבילות שלו?`)) return; await parent.removeEntry(entryName, { recursive: true }); try { await parent.getDirectoryHandle(entryName); throw new Error("הדפדפן דיווח שהתיקייה עדיין קיימת."); } catch (error) { if (error.name !== "NotFoundError") throw error; } clients = clients.filter((item) => item.id !== client.id); await setting("clients", clients); renderClients(); summary.textContent = "הלקוח נמחק לצמיתות."; summary.classList.remove("workspace-ready"); onDeleted?.(client.id); } catch (error) { if (error.name !== "AbortError") { const message = `לא ניתן למחוק לקוח: ${error.message}`; summary.textContent = message; summary.classList.remove("workspace-ready"); onError(message); } } });
  templateButton.addEventListener("click", async () => { try { const [handle] = await window.showOpenFilePicker({ multiple: false, types: [{ description: "תבנית Rivhit", accept: { "text/plain": [".TXT", ".txt"] } }] }); await validateTemplateFile(await handle.getFile()); await setting("canonical-template", handle); templateSummary.textContent = `תבנית כללית נבחרה: ${handle.name}.`; templateSummary.classList.add("workspace-ready"); onTemplate(handle); } catch (error) { if (error.name !== "AbortError") onError(`לא ניתן לבחור תבנית Rivhit: ${error.message}`); } });
  (async () => { try { const storedClients = await setting("clients") || []; clients = (await Promise.all(storedClients.map(async (client) => { try { const config = await readConfig(client.directory); return { ...client, id: config.clientId || client.id, clientName: config.clientName }; } catch (error) { if (error.name === "NotFoundError") return null; throw error; } }))).filter(Boolean); if (clients.length !== storedClients.length) await setting("clients", clients); renderClients(); const template = await setting("canonical-template"); if (template) { await validateTemplateFile(await template.getFile()); templateSummary.textContent = `תבנית כללית נבחרה: ${template.name}.`; templateSummary.classList.add("workspace-ready"); onTemplate(template); } } catch (error) { onError(`לא ניתן לשחזר את ההגדרות המקומיות: ${error.message}`); } })();
}
