import { normalizeWorkspaceConfig, validateRivhitTemplateText } from "./workspace-core.js";
import { createDeclaration, listDeclarations, loadDeclaration } from "./declaration-store.js";
import { declarationMonth } from "./declaration-core.js";

const configName = "workspace.json", databaseName = "rivhit-local-workspaces-v1", templateName = "PKUDA_AI_TEST.TXT", decoder = new TextDecoder("windows-1255");
function openDatabase() { return new Promise((resolve, reject) => { const request = indexedDB.open(databaseName, 1); request.onupgradeneeded = () => request.result.createObjectStore("settings"); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function setting(key, value) { const database = await openDatabase(); return new Promise((resolve, reject) => { const transaction = database.transaction("settings", value === undefined ? "readonly" : "readwrite"), request = value === undefined ? transaction.objectStore("settings").get(key) : transaction.objectStore("settings").put(value, key); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }).finally(() => database.close()); }
async function validateTemplateFile(file) { const result = validateRivhitTemplateText(decoder.decode(await file.arrayBuffer())); if (!result.valid) throw new Error(result.error); }
async function readConfig(directory) { const handle = await directory.getFileHandle(configName), result = normalizeWorkspaceConfig(JSON.parse(await (await handle.getFile()).text())); if (!result.valid) throw new Error(result.error); return result.config; }
async function writeConfig(directory, config) { const handle = await directory.getFileHandle(configName, { create: true }), writable = await handle.createWritable(); try { await writable.write(JSON.stringify(config, null, 2)); } finally { await writable.close(); } }
async function writeTemplate(directory, file) { const handle = await directory.getFileHandle(templateName, { create: true }), writable = await handle.createWritable(); try { await writable.write(await file.arrayBuffer()); } finally { await writable.close(); } return handle; }
async function ensureAccess(directory) { let permission = await directory.queryPermission({ mode: "readwrite" }); if (permission !== "granted") permission = await directory.requestPermission({ mode: "readwrite" }); if (permission !== "granted") throw new Error("לא ניתנה הרשאה לתיקייה המקומית."); }
function directoryName(clientName) { return clientName.replace(/[\\/:*?"<>|]/g, "-").replace(/[. ]+$/, "").replace(/\s+/g, " ").trim(); }

export function setupWorkspaceControls({ clientList, showNewButton, openExistingButton, archivedToggle, dataRootButton, dataRootSummary, templateButton, creationPanel, createButton, deleteButton, archiveButton, restoreButton, saveClientButton, clientMenu, clientMenuName, clientNameInput, clientActivityInput, clientKindInput, businessActivityInput, businessKindInput, summary, templateSummary, onDataRoot, onTemplate, onDeclaration, onUpdated, onArchived, onDeleted, onError }) {
  if (!("showDirectoryPicker" in window) || !("showOpenFilePicker" in window) || !("indexedDB" in window)) { dataRootButton.disabled = true; templateButton.disabled = true; summary.textContent = "נדרש Edge או Chrome עם גישה לתיקיות מקומיות."; return; }
  let activeClients = [], archivedClients = [], dataRoot = null, canonicalTemplate = null, menuClient = null, showingArchived = false, activeClientId = null, activeDeclarationId = null, expandedClientId = null;
  templateButton.disabled = true;
  const showDataRoot = () => { dataRootButton.hidden = Boolean(dataRoot); dataRootSummary.textContent = dataRoot ? "תיקיית נתונים: " + dataRoot.name : "טרם נבחרה תיקיית נתונים."; dataRootSummary.classList.toggle("workspace-ready", Boolean(dataRoot)); };
  const setTemplate = async (handle) => { canonicalTemplate = handle; templateSummary.textContent = "תבנית כללית: " + templateName + "."; templateSummary.classList.add("workspace-ready"); onTemplate(handle); try { await setting("canonical-template", handle); } catch (error) { console.warn("לא ניתן לזכור את תבנית Rivhit להפעלה הבאה.", error); } };
  const clearTemplate = () => { canonicalTemplate = null; onTemplate(null); templateSummary.textContent = "בתיקייה זו טרם נבחרה תבנית Rivhit כללית."; templateSummary.classList.remove("workspace-ready"); };
  const loadTemplateFromRoot = async () => { if (!dataRoot) return false; try { const common = await dataRoot.getDirectoryHandle("common"), handle = await common.getFileHandle(templateName); await validateTemplateFile(await handle.getFile()); await setTemplate(handle); return true; } catch (error) { if (error.name === "NotFoundError") return false; throw error; } };
  const visibleClients = () => showingArchived ? archivedClients : activeClients;
  const nextDeclarationMonth = (client) => { const date = new Date(); let month = declarationMonth(date); while ((client.declarations || []).some((item) => item.declaration.month === month)) { date.setMonth(date.getMonth() + 1); month = declarationMonth(date); } return month; };
  const hideMenu = () => { menuClient = null; if (clientMenu.open) clientMenu.close(); };
  const renderClients = () => {
    clientList.replaceChildren();
    for (const client of visibleClients()) { const item = document.createElement("div"), row = document.createElement("div"), choose = document.createElement("button"), icon = document.createElement("span"), label = document.createElement("span"), menu = document.createElement("button"), expanded = expandedClientId === client.id; item.className = "client-tree-item"; row.className = "client-row"; choose.type = menu.type = "button"; choose.className = "client-choice"; icon.className = "tree-item-icon"; icon.setAttribute("aria-hidden", "true"); icon.textContent = "▣"; label.className = "tree-item-label"; label.textContent = client.clientName; choose.append(icon, label); choose.classList.toggle("active-client", client.id === activeClientId); choose.classList.toggle("is-expanded", expanded); choose.setAttribute("aria-expanded", String(expanded)); choose.disabled = Boolean(client.config.archived); if (client.config.archived) choose.title = "יש לשחזר לקוח לפני בחירה בו."; menu.className = "client-overflow"; menu.textContent = "⋯"; menu.setAttribute("aria-label", "פעולות עבור " + client.clientName); choose.addEventListener("click", async () => { try { await toggleClient(client); } catch (error) { if (error.name !== "AbortError") onError("לא ניתן לפתוח הצהרות לקוח: " + error.message); } }); menu.addEventListener("click", () => showMenu(client)); row.append(choose, menu); item.append(row); if (expanded) { const declarations = document.createElement("div"); declarations.className = "declaration-list"; for (const declarationItem of client.declarations || []) { const select = document.createElement("button"); select.type = "button"; select.className = "declaration-choice"; select.textContent = `הצהרה · ${declarationItem.declaration.month} · ${declarationItem.declaration.status === "open" ? "טיוטה" : "סגורה"}`; select.classList.toggle("active-declaration", declarationItem.declaration.declarationId === activeDeclarationId); select.addEventListener("click", async () => { try { await selectDeclaration(client, declarationItem.declaration.month); } catch (error) { onError("לא ניתן לפתוח הצהרה: " + error.message); } }); declarations.append(select); } const create = document.createElement("button"); create.type = "button"; create.className = "new-declaration"; create.textContent = `+ הצהרה חדשה · ${nextDeclarationMonth(client)}`; create.addEventListener("click", async () => { try { await createCurrentDeclaration(client); } catch (error) { onError("לא ניתן ליצור הצהרה: " + error.message); } }); declarations.append(create); item.append(declarations); } clientList.append(item); }
    if (!visibleClients().length) { const empty = document.createElement("p"); empty.className = "clients-empty"; empty.textContent = showingArchived ? "אין לקוחות בארכיון." : "אין לקוחות בתיקייה זו."; clientList.append(empty); }
    archivedToggle.hidden = !archivedClients.length; archivedToggle.textContent = showingArchived ? "לקוחות פעילים" : "ארכיון (" + archivedClients.length + ")";
  };
  const showMenu = (client) => { menuClient = client; clientMenuName.textContent = client.clientName; businessActivityInput.value = client.config.businessActivity; businessKindInput.value = client.config.businessKind; const rootClient = Boolean(client.parent); saveClientButton.hidden = !rootClient; archiveButton.hidden = !rootClient || client.config.archived; restoreButton.hidden = !rootClient || !client.config.archived; deleteButton.hidden = !rootClient; clientMenu.showModal(); };
  const scanClientsFromRoot = async () => { if (!dataRoot) return; const parent = await dataRoot.getDirectoryHandle("clients"), found = []; for await (const [entryName, handle] of parent.entries()) { if (handle.kind !== "directory") continue; try { const config = await readConfig(handle); found.push({ id: config.clientId || entryName, clientName: config.clientName, directory: handle, parent, entryName, config, declarations: await listDeclarations(handle) }); } catch {} } found.sort((left, right) => left.clientName.localeCompare(right.clientName, "he")); activeClients = found.filter((client) => !client.config.archived); archivedClients = found.filter((client) => client.config.archived); if (!activeClients.some((client) => client.id === activeClientId)) { activeClientId = null; activeDeclarationId = null; } renderClients(); };
  const setDataRoot = async (directory, restoring = false) => { if (!restoring) { await ensureAccess(directory); await directory.getDirectoryHandle("common", { create: true }); await directory.getDirectoryHandle("clients", { create: true }); await setting("data-root", directory); } dataRoot = directory; templateButton.disabled = false; showDataRoot(); onDataRoot(dataRoot); try { if (!await loadTemplateFromRoot()) clearTemplate(); await scanClientsFromRoot(); } catch (error) { if (!restoring || error.name !== "NotAllowedError") throw error; } };
  const selectDeclaration = async (client, month) => { await ensureAccess(client.directory); const selected = await loadDeclaration(client.directory, month); const workspace = { directory: client.directory, config: client.config }; if (await onDeclaration({ workspace, ...selected }) === false) return; activeClientId = client.id; activeDeclarationId = selected.declaration.declarationId; summary.textContent = `נבחרה הצהרה: «${client.clientName}» · ${selected.declaration.month}.`; summary.classList.add("workspace-ready"); renderClients(); };
  const toggleClient = async (client) => { await ensureAccess(client.directory); activeClientId = client.id; expandedClientId = expandedClientId === client.id ? null : client.id; renderClients(); };
  const createCurrentDeclaration = async (client) => { const month = nextDeclarationMonth(client), created = await createDeclaration(client.directory, { clientId: client.config.clientId, month }); await scanClientsFromRoot(); expandedClientId = client.id; await selectDeclaration(activeClients.find((item) => item.id === client.id), created.declaration.month); };
  const openExisting = async () => { const directory = await window.showDirectoryPicker({ mode: "readwrite", startIn: "documents" }); const config = await readConfig(directory); const temporary = { id: config.clientId || directory.name, clientName: config.clientName, directory, parent: null, config, declarations: await listDeclarations(directory) }; expandedClientId = temporary.id; activeClients = [temporary]; archivedClients = []; renderClients(); };
  const createNew = async () => { const clientName = clientNameInput.value.trim(), businessActivity = clientActivityInput.value.trim(), name = directoryName(clientName); if (!clientName || !businessActivity) throw new Error("יש למלא שם לקוח וסוג פעילות."); if (!name) throw new Error("שם הלקוח אינו יכול לשמש כשם תיקייה."); if (!dataRoot) throw new Error("יש לבחור תחילה תיקיית נתונים."); const parent = await dataRoot.getDirectoryHandle("clients", { create: true }), directory = await parent.getDirectoryHandle(name, { create: true }); try { await readConfig(directory); throw new Error("בתיקייה זו כבר קיים לקוח. יש לפתוח אותו במקום ליצור מחדש."); } catch (error) { if (error.message.includes("כבר קיים")) throw error; if (error.name !== "NotFoundError") throw error; } const config = { schemaVersion: 1, clientId: crypto.randomUUID(), clientName, businessActivity, businessKind: clientKindInput.value, archived: false }; await createDeclaration(directory, { clientId: config.clientId, month: declarationMonth(new Date()) }); await writeConfig(directory, config); creationPanel.hidden = true; clientNameInput.value = ""; clientActivityInput.value = ""; expandedClientId = config.clientId; await scanClientsFromRoot(); };
  const saveMenuConfig = async (changes, callback) => { if (!menuClient || !menuClient.parent) throw new Error("פעולה זו זמינה רק ללקוח שבתיקיית הנתונים."); const result = normalizeWorkspaceConfig({ ...menuClient.config, ...changes }); if (!result.valid) throw new Error(result.error); await writeConfig(menuClient.directory, result.config); const saved = { ...menuClient, config: result.config, clientName: result.config.clientName }; if (result.config.archived && activeClientId === saved.id) activeClientId = null; hideMenu(); await scanClientsFromRoot(); callback?.(saved); };
  showDataRoot(); renderClients();
  clientMenu.addEventListener("close", () => { menuClient = null; });
  dataRootButton.addEventListener("click", async () => { try { await setDataRoot(await window.showDirectoryPicker({ mode: "readwrite", startIn: "documents" })); } catch (error) { if (error.name !== "AbortError") onError("לא ניתן לבחור תיקיית נתונים: " + error.message); } });
  showNewButton.addEventListener("click", () => { creationPanel.hidden = !creationPanel.hidden; if (!creationPanel.hidden) clientNameInput.focus(); });
  openExistingButton?.addEventListener("click", async () => { try { await openExisting(); } catch (error) { if (error.name !== "AbortError") onError("לא ניתן לפתוח לקוח: " + error.message); } });
  archivedToggle.addEventListener("click", () => { showingArchived = !showingArchived; hideMenu(); renderClients(); });
  createButton.addEventListener("click", async () => { try { await createNew(); } catch (error) { if (error.name !== "AbortError") onError("לא ניתן ליצור לקוח: " + error.message); } });
  saveClientButton.addEventListener("click", async () => { try { await saveMenuConfig({ businessActivity: businessActivityInput.value.trim(), businessKind: businessKindInput.value }, onUpdated); } catch (error) { onError("לא ניתן לשמור את פרטי הלקוח: " + error.message); } });
  archiveButton.addEventListener("click", async () => { try { await saveMenuConfig({ archived: true }, onArchived); } catch (error) { onError("לא ניתן לארכב לקוח: " + error.message); } });
  restoreButton.addEventListener("click", async () => { try { await saveMenuConfig({ archived: false }, (saved) => { showingArchived = false; renderClients(); onUpdated(saved); }); } catch (error) { onError("לא ניתן לשחזר לקוח: " + error.message); } });
  deleteButton.addEventListener("click", async () => { try { if (!menuClient?.parent) throw new Error("פעולה זו זמינה רק ללקוח שבתיקיית הנתונים."); const client = menuClient; if (!window.confirm("למחוק לצמיתות את «" + client.clientName + "»? יימחקו גם ההיסטוריה, קובצי PDF, TXT וכל החבילות.")) return; await ensureAccess(client.parent); const target = await client.parent.getDirectoryHandle(client.entryName); if (!await target.isSameEntry(client.directory)) throw new Error("התיקייה שנבחרה אינה תיקיית הלקוח. המחיקה בוטלה."); await client.parent.removeEntry(client.entryName, { recursive: true }); hideMenu(); await scanClientsFromRoot(); onDeleted?.(client.id); } catch (error) { if (error.name !== "AbortError") onError("לא ניתן למחוק לקוח: " + error.message); } });
  templateButton.addEventListener("click", async () => { try { if (!dataRoot) throw new Error("יש לבחור תחילה תיקיית נתונים."); const [source] = await window.showOpenFilePicker({ multiple: false, types: [{ description: "תבנית Rivhit", accept: { "text/plain": [".TXT", ".txt"] } }] }), file = await source.getFile(); await validateTemplateFile(file); const common = await dataRoot.getDirectoryHandle("common", { create: true }); await setTemplate(await writeTemplate(common, file)); } catch (error) { if (error.name !== "AbortError") { const message = "לא ניתן לבחור תבנית Rivhit: " + error.message; templateSummary.textContent = message; templateSummary.classList.remove("workspace-ready"); onError(message); } } });
  (async () => { try { const storedRoot = await setting("data-root"); if (storedRoot) await setDataRoot(storedRoot, true); } catch (error) { onError("לא ניתן לשחזר את ההגדרות המקומיות: " + error.message); } })();
  const refreshFromUserAction = async () => { if (!dataRoot) return; await ensureAccess(dataRoot); await scanClientsFromRoot(); if (!await loadTemplateFromRoot()) clearTemplate(); };
  const showActiveClients = () => { showingArchived = false; hideMenu(); renderClients(); };
  return { clearPending: hideMenu, refreshFromUserAction, showActiveClients, hasCanonicalTemplate: () => Boolean(canonicalTemplate) };
}
