const labels={recipient_name:"שם המקבל",date:"תאריך",supplier_name:"שם הספק",supplier_vat_id:"מספר עוסק מורשה של הספק",invoice_number:"מספר חשבונית",total_amount:"סך הכל",allocation_number:"מספר הקצאה",purpose:"עבור מה התקבלה החשבונית",transaction_number:"מספר עסקה",currency:"מטבע",language:"שפת המסמך"};
const numeric=new Set(["total_amount"]),input=document.querySelector("#image"),model=document.querySelector("#model"),previews=document.querySelector("#previews"),recognize=document.querySelector("#recognize"),stop=document.querySelector("#stop"),status=document.querySelector("#status"),results=document.querySelector("#results"),template=document.querySelector("#document-template");let activeController=null,activeRequestId=null,stopRequested=false;
fetch("/api/health").then(response=>response.json()).then(data=>{if([...(data.models||[])].includes(data.model))model.value=data.model}).catch(()=>{});
if(location.protocol==="file:"){status.textContent="פתח את הכתובת המקומית מ-app.py, לא קובץ HTML ישירות.";input.disabled=true}
input.addEventListener("change",()=>{previews.replaceChildren();results.replaceChildren();results.hidden=true;let files=[...input.files];recognize.disabled=!files.length;status.textContent=files.length?`נבחרו ${files.length} קבצים.`:"";for(const file of files){let figure=document.createElement("figure"),image=document.createElement("img"),caption=document.createElement("figcaption");image.src=URL.createObjectURL(file);image.alt=file.name;caption.textContent=file.name;figure.append(image,caption);previews.append(figure)}});
recognize.addEventListener("click",async()=>{let files=[...input.files],selectedModel=model.value,ok=0;stopRequested=false;recognize.disabled=true;model.disabled=true;stop.hidden=false;stop.disabled=false;results.replaceChildren();results.hidden=false;for(let n=0;n<files.length&&!stopRequested;n++){let file=files[n];activeController=new AbortController();activeRequestId=crypto.randomUUID();status.textContent=`מזהה ${n+1} מתוך ${files.length}: ${file.name}`;try{let response=await fetch("/api/recognize",{method:"POST",signal:activeController.signal,headers:{"Content-Type":file.type,"X-Source-Filename":file.name,"X-Gemini-Model":selectedModel,"X-Request-ID":activeRequestId},body:file}),result=await response.json();if(!response.ok)throw Error(result.error||"הזיהוי נכשל.");renderDocument(result,file);ok++}catch(error){if(!stopRequested)errorCard(file,error instanceof TypeError?`הבקשה לשרת המקומי נכשלה (${error.message}). בדוק את /api/health.`:error.message)}finally{activeController=null;activeRequestId=null}}status.textContent=stopRequested?`העיבוד נעצר. הושלמו ${ok} מתוך ${files.length}.`:`הושלמו ${ok} מתוך ${files.length}. ניתן לערוך ולשמור כל מסמך.`;recognize.disabled=false;model.disabled=false;stop.disabled=true;stop.hidden=true});
stop.addEventListener("click",()=>{if(!activeController)return;stopRequested=true;stop.disabled=true;status.textContent="עוצר את העיבוד…";let requestId=activeRequestId;activeController.abort();fetch("/api/cancel",{method:"POST",headers:{"X-Request-ID":requestId}}).catch(()=>{})});
function renderDocument(result,file){if(!Array.isArray(result.invoices)||!result.invoices.length||!result.invoices.every(validInvoice))throw Error("השרת החזיר JSON בפורמט ישן. רענן את הדף והפעל את run.ps1.");let sourceKey=crypto.randomUUID();result.invoices.forEach((invoice,index)=>renderInvoice(result,invoice,file,index,sourceKey));}
function validInvoice(invoice){return Object.keys(labels).every(name=>invoice[name]&&Object.hasOwn(invoice[name],"value")&&Object.hasOwn(invoice[name],"evidence"));}
function renderInvoice(result,invoice,file,index,sourceKey){let fragment=template.content.cloneNode(true),card=fragment.querySelector(".document");card.dataset.sourceImage=file.name;card.dataset.sourceKey=sourceKey;card.dataset.invoiceIndex=index;card.querySelector("h2").textContent=result.invoices.length===1?file.name:`${file.name} — מסמך ${index+1}`;card.querySelector(".outcome").textContent="זוהה ונשמר";let image=card.querySelector(".document-preview");image.src=URL.createObjectURL(file);image.alt=file.name;let form=card.querySelector(".fields");for(let [name,label] of Object.entries(labels)){let row=document.createElement("label"),title=document.createElement("span"),box=document.createElement("input"),evidence=document.createElement("small"),entry=invoice[name];row.className="field";title.textContent=label;box.name=name;box.value=Array.isArray(entry.value)?entry.value.join(", "):entry.value??"";box.type=numeric.has(name)?"number":"text";box.step="0.01";box.dir="auto";evidence.textContent=entry.evidence?`מקור: ${entry.evidence}`:"לא נמצא";box.addEventListener("input",()=>syncInvoice(card,result,index));row.append(title,box,evidence);form.append(row)}card.querySelector(".save").addEventListener("click",()=>saveDocument(card,result));results.append(fragment);syncInvoice(results.lastElementChild,result,index)}
function syncInvoice(card,result,index){let invoice=result.invoices[index];for(let name of Object.keys(labels)){let value=card.querySelector(`[name="${name}"]`).value.trim();if(name==="language"&&value!==""){let values=value.split(",").map(item=>item.trim().toLowerCase()).filter(Boolean);value=values.length===1?values[0]:values}else if(numeric.has(name)&&value!=="")value=Number(value);else if(value==="")value=null;invoice[name]={value,evidence:invoice[name]?.evidence??null}}for(let item of results.querySelectorAll(`[data-source-key="${card.dataset.sourceKey}"] .json`))item.textContent=JSON.stringify(result,null,2)}
async function saveDocument(card,result){let button=card.querySelector(".save"),saveStatus=card.querySelector(".save-status");button.disabled=true;saveStatus.textContent="שומר…";try{let response=await fetch("/api/save",{method:"POST",headers:{"Content-Type":"application/json","X-Source-Filename":card.dataset.sourceImage},body:JSON.stringify(result)}),saved=await response.json();if(!response.ok)throw Error(saved.error||"השמירה נכשלה.");Object.assign(result,saved);for(let item of results.querySelectorAll(`[data-source-key="${card.dataset.sourceKey}"] .json`))item.textContent=JSON.stringify(result,null,2);saveStatus.textContent="נשמר"}catch(error){saveStatus.textContent=error.message}finally{button.disabled=false}}
function errorCard(file,message){let card=document.createElement("article"),heading=document.createElement("h2"),text=document.createElement("p");card.className="document card error";heading.textContent=file.name;text.textContent=`נכשל: ${message}`;card.append(heading,text);results.append(card)}
